### ISSUE TITLE
more TTL options

### ISSUE THREAD

**Issue by jjurkus** [Jehops/zap#4]
Would it be an idea to have more granular control of the TTL of the snapshots? For instance, if you make a snapshot every 15 minutes, but want to keep these for only an hour or four.

**Comment by Jehops** [comment]
Creating snapshots is always a very light operation, but destroying them may be very heavy.  So, I don't recommend that you create a cron job to destroy snapshots that often.  It's for that reason that I set the minimum TTL to one day.

**Comment by Jehops** [comment]
Following up on the last comment, I am closing this issue.  If you have a convincing argument, please re-open it.

**Comment by brenc** [comment]
@Jehops - I'm actually looking at doing snapshots every minute but I'm not sure I want to be deleting 1440+ snapshots once per day. Even doing snapshots every five minutes would be 288 snapshots a day to be destroyed. Wouldn't it be better to destroy more often? Gut feeling says yes, but I honestly don't know because I haven't attempted this.

We use FreeNAS primarily right now which does snaps at a minimum of every five minutes. It appears to prune them after doing snaps which seems most logical to me. Interested in hearing about your experiences with this.

**Comment by Jehops** [comment]
I still think it makes more sense to delete less frequently unless you want to be thrashing your disk regularly.
